import {
  Body,
  Title,
  LargeTitle,
  SubheadEmphasized,
  Subhead,
  BodyEmphasized,
  Statement,
  StatementHighlight,
  ButtonLabel,
  RockerSwitchInputValue,
  Label,
  Value,
  Footnote,
  FootnoteEmphasized,
  BigAmount,
  BigAmountCurrency,
  SettingsTitle,
  SettingsTitleEmphasized,
} from './Typography';

const Text = {
  Body,
  Title,
  LargeTitle,
  SubheadEmphasized,
  Subhead,
  BodyEmphasized,
  Statement,
  StatementHighlight,
  ButtonLabel,
  RockerSwitchInputValue,
  Label,
  Value,
  FootnoteEmphasized,
  Footnote,
  BigAmount,
  BigAmountCurrency,
  SettingsTitle,
  SettingsTitleEmphasized,
};
export default Text;
